use_frameworks!

platform :ios, '9.0'

target 'VcomKeyboard_Example' do
  pod 'VcomKeyboard', :path => '../'

  target 'VcomKeyboard_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
